function radPat_Front = radpat_front_Control(steerAngle)

  % Elevation angle intervals with beam data:
  int1 = 1:1801;
  int2 = 2001:3801;
  int3 = 4001:5801;

  % Loading the right.mat file according to beam steering:
  if steerAngle == 0
    cont = load('front1030_cont_0.mat');
  elseif steerAngle == 15
    cont = load('front030_cont_15.mat');
  elseif steerAngle == 35
    cont = load('front1030_cont_35.mat');
  elseif steerAngle == 55
    cont = load('front1030_cont_55.mat');
  elseif steerAngle == -15
    cont = load('front1030_cont_neg15.mat');
  elseif steerAngle == -35
    cont = load('front1030_cont_neg35.mat');
  else
    cont = load('front1030_cont_neg50.mat');
  end
  radPat_Front = [cont.front_data_cont2(int1)';...
                  cont.front_data_cont3(int3)';...
                  cont.front_data_cont3(int2)';...
                  cont.front_data_cont3(int1)';...
                  cont.front_data_cont4(int3)';...
                  cont.front_data_cont4(int2)';...
                  cont.front_data_cont4(int1)';...
                  cont.front_data_cont5(int3)';...
                  cont.front_data_cont5(int2)';...
                  cont.front_data_cont5(int1)';...
                  cont.front_data_cont6(int3)';...
                  cont.front_data_cont6(int2)';...
                  cont.front_data_cont6(int1)';...
                  cont.front_data_cont7(int3)';...
                  cont.front_data_cont7(int2)'];
end